/* Generated By:JavaCC: Do not edit this line. SQL_Query_ValidatorConstants.java */
package GroupProject_Part3_Package;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface SQL_Query_ValidatorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SELECT = 5;
  /** RegularExpression Id. */
  int FROM = 6;
  /** RegularExpression Id. */
  int WHERE = 7;
  /** RegularExpression Id. */
  int INSERT = 8;
  /** RegularExpression Id. */
  int INTO = 9;
  /** RegularExpression Id. */
  int VALUES = 10;
  /** RegularExpression Id. */
  int UPDATE = 11;
  /** RegularExpression Id. */
  int SET = 12;
  /** RegularExpression Id. */
  int DELETE = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int LPARENTHESIS = 15;
  /** RegularExpression Id. */
  int RPARENTHESIS = 16;
  /** RegularExpression Id. */
  int EQUAL = 17;
  /** RegularExpression Id. */
  int IDENTIFIER = 18;
  /** RegularExpression Id. */
  int VALUE = 19;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"SELECT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"UPDATE\"",
    "\"SET\"",
    "\"DELETE\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "<IDENTIFIER>",
    "<VALUE>",
    "\";\"",
  };

}
